version: '3.8'
services:
  app:
    build: .
    ports:
      - "8002:8000"
    volumes:
      - /home/darinka/miem_llm_model/results/z1ewnsuy:/model
      - /home/darinka/miem_llm_model/results/tokenizer:/tokenizer
    environment:
      - MODELNAME=/model
      - TOKENIZER=/tokenizer
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

